src/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.template.base import kwarg_re
from django.urls import path

from authentication.forms import LoginForm
from authentication.views import DashboardView

urlpatterns = [
    path('', auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True,
        authentication_form=LoginForm
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard')
]

src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from product.views.product import CreateProductView, ProductView
from product.views.variant import VariantView, VariantCreateView, VariantEditView

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('list/', ProductView.as_view(), name='list.product'),
]

src/authentication/models.py
from django.db import models

# Create your models here.

src/product/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Variant(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Product(models.Model):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ProductVariant(models.Model):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ProductVariantPrice(models.Model):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                              related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

src/authentication/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    error_css_class = 'is-invalid'

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control form-control-user', 'placeholder': 'Enter your username'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-user', 'placeholder': 'Enter your password'}
    ))

src/product/forms.py
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

src/authentication/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django import views
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class DashboardView(views.generic.TemplateView):
    template_name = 'dashboard.html'

src/product/views/product.py
from django.shortcuts import render
from django.views import generic, View 
from product.models import Variant, Product

import json

from product.utils import createProduct, createProductVarient,createProductVariantPrice

class  CreateProductView(View):

    def get(self, request):

        context = {}
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())
        

        return render (request,'products/create.html', context )

    def post(self, request):

        data = json.loads(request.body)

        product =createProduct(data)

        variants_obj_dict = createProductVarient(data, product)


        createProductVariantPrice(data, variants_obj_dict, product)

        context = {}
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())

        return render (request,'products/create.html', context )


class ProductView(generic.ListView):
    template_name = "products/list.html"
    paginate_by = 2
    model = Product
    context_object_name = "products"    

    def get_queryset(self):
        filter_string = {}
        for key in self.request.GET:
            if self.request.GET.get(key) and key != "page":   # exludes pagination parameter page
                filter_string[key] = self.request.GET.get(key)
        print("filter_string", filter_string)
        return Product.objects.filter(**filter_string).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        variants = Variant.objects.all()
        context["variants"] = variants

        #  to  add  query parameter  in pagination 
        queyr_paremeter = self.request.GET.copy()
        parameters = queyr_paremeter.pop('page', True) and queyr_paremeter.urlencode()
        context["parameters"] = parameters
        
        return context

src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print("in varient")
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

src/authentication/templates/login.html
{% extends 'website/base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" method="post" novalidate>
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{ form.username }}
                                            <div class="text-danger list-unstyled">
                                                {{ form.username.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            {{ form.password }}
                                            <div class="text-danger list-unstyled">
                                                {{ form.password.errors }}
                                            </div>
                                        </div>

                                        {#                                        {{ form.as_p }}#}
                                        <button class="btn btn-primary btn-user btn-block" type="submit">Login</button>
                                    </form>
                                    <hr>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

src/product/templates/products/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Product {% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
    <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
</div>

<div id="app">
    <create-product :variants="{{variants|safe}}"></create-product>
</div>

{% endblock %}

src/product/templates/products/list.html
{% extends 'backend/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Products</h1>
</div>


<div class="card">
    <form action="" method="get" class="card-header">
        <div class="form-row justify-content-between">
            <div class="col-md-2">
                <input type="text" name="title" placeholder="Product Title" class="form-control">
            </div>
            <div class="col-md-2">
                <select name="productvariant__variant_title" id="" class="form-control">
                    <option selected disabled>--Select A Variant--</option>
                    {% for variant in variants %}
                    <option disabled>{{variant.title}}</option>
                      {% for  productVariant in variant.productvariant_set.all|dictsort:'variant_title'%}
                      {% ifchanged  %}  
                      <option  value={{productVariant.variant_title}} >&nbsp;{{productVariant.variant_title}}</option>   
                      {% endifchanged %}
                      {% endfor %}

                    {% endfor %}

                </select>
            </div>

            <div class="col-md-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Price Range</span>
                    </div>
                    <input type="text" name="productvariantprice__price__gte" aria-label="First name" placeholder="From"
                           class="form-control">
                    <input type="text" name="productvariantprice__price__lte" aria-label="Last name" placeholder="To" class="form-control">
                </div>
            </div>
            <div class="col-md-2">
                <input type="date" name="created_at__contains" placeholder="Date" class="form-control">
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>



  
    <div class="card-body">
        <div class="table-response">
            
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Variant</th>
                    <th width="150px">Action</th>
                </tr>
                </thead>

                <tbody>
                    {% for product in products  %} 
                <tr>
                    <td>{{product.id}}</td>
                    <td>{{ product.title }} <br> Created at : {{product.created_at| timesince}} ago </td>
                    <td>{{ product.description }}</td>
                    
                    <td>
                        {% for variantPrice in product.productvariantprice_set.all.all %}
                        <dl class="row mb-0" style="height: 80px; overflow: hidden" id="">

                           

                            <dt class="col-sm-3 pb-0">

                              
            
                                {{variantPrice.product_variant_one.variant_title}}/{{variantPrice.product_variant_two.variant_title}}/{{variantPrice.product_variant_three.variant_title}}

                                
                            </dt>
                            <dd class="col-sm-9">
                                <dl class="row mb-0">
                                    <dt class="col-sm-4 pb-0">Price :{{variantPrice.price}} </dt>
                                    <dd class="col-sm-8 pb-0">InStock :{{variantPrice.stock}} </dd>
                                </dl>
                            </dd>

                        </dl>
                       
                        {% endfor %}

                        <button onclick="$('#variant').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                        </button>
                       
                    </td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="" class="btn btn-success">Edit</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>

    </div>

    

    <div class="card-footer">
        <div class="row justify-content-between">
            <div class="col-md-6">
                
                <p>Showing {{ page_obj.start_index }} to {{ page_obj.end_index }} out  of {{ page_obj.paginator.count }}</p>
            </div>
            <div class="col-md-2">
               


                <!-- paginator -->

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                      {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.previous_page_number }}& {{ parameters }}">&lt;</a>
                        </li>
                      {% else %}
                        <li class="page-item disabled">
                          <a class="page-link" href="#" tabindex="-1" aria-disabled="True">&lt;</a>
                        </li>
                      {% endif %}
                      {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                          <li class="page-item active" aria-current="page">
                            <span class="page-link">
                              {{ i }}
                              <span class="sr-only">(current)</span>
                            </span>
                          </li>
                        {% else %}
                          <li class="page-item"><a class="page-link" href="?page={{ i }} & {{ parameters }}">{{ i }}</a></li>
                        {% endif %}
                      {% endfor %}
                      {% if page_obj.has_next %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.next_page_number }} & {{ parameters }}">&gt;</a>
                        </li>
                      {% else %}
                        <li class="page-item disabled">
                          <a class="page-link" href="#" tabindex="-1" aria-disabled="True">&gt;</a>
                        </li>
                      {% endif %}
                    </ul>
                  </nav>






            </div>
        </div>
    </div>
</div>
{% endblock %}

src/product/templates/variants/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Variant {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Product Variant</h1>
        <a href="{% url 'product:variants' %}" class="float-right btn btn-primary">All Variant</a>
    </div>

    <div class="row justify-content-center">
        <form class="col-md-6" method="post" novalidate>
            {% csrf_token %}
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.title.label }}</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.active }}
                        <label class="form-check-label" for="active">{{ form.active.label }}</label>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

src/product/templates/variants/list.html
{% extends 'backend/base.html' %}

{% block title %} Create Variant {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Product Variant</h1>
        <a href="{% url 'product:create.variant' %}" class="float-right btn btn-primary">+ New Variant</a>
    </div>

    <div class="card shadow mb-4">
        <form action="?" method="get" class="card-header py-3">
            <div class="form-row">
                <div class="col-md-3">
                    <input type="text" name="title__icontains" value="{{ request }}" placeholder="Serch"
                           class="form-control">
                </div>
                <div class="col-md-1">
                    <button class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for variant in variant_list %}
                        <tr>
                            <td>{{ variant.title }}</td>
                            <td>{{ variant.description }}</td>
                            <td>{{ variant.active }}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                    <a href="{% url 'product:update.variant' variant.id %}"
                                       class="btn btn-primary">Edit</a>
                                    <button type="button" class="btn btn-danger">Delete</button>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/product/variants/?browse={{ input }}&page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/product/variants/?browse={{ input }}&page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/backend/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Home
        {% endblock %}-Mediusware
    </title>
    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
          integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body id="page-top">
<div id="wrapper">

    {% include 'backend/particals/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            {% include 'backend/particals/navbar.html' %}
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                {% block content %} {% endblock %}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website 2021</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
<script src="{% static '/js/app.js' %}"></script>
</body>
</html>

src/templates/backend/particals/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Product</span>
        </a>
        <div id="collapsePages" class="collapse {% if product %} show {% endif %}" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Product Option:</h6>
                <a class="collapse-item" href="{% url 'product:variants' %}">Variant</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Product:</h6>
                <a class="collapse-item" href="{% url 'product:create.product' %}">Create Product</a>
                <a class="collapse-item" href="{% url 'product:list.product' %}">All Product</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

src/templates/website/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Home
        {% endblock %}-Mediusware
    </title>
    <!-- Custom fonts for this template-->
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body class="bg-gradient-primary">
{% block content %}

{% endblock %}

</body>
</html>